services:

  db:
    image: postgres:14.5
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ddgn
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn DockerDjangoAutenNginxGunicorn.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=DockerDjangoAutenNginxGunicorn.settings
      - POSTGRES_DB=ddgn
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db